version: '3.8'

services:
  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
    ports:
      - "3308:3306"
#    expose:
#      - "3306"
    container_name: mysql2

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=mysql2
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_DATABASE=test
#     DB_PORT=3306, not 3308 because the app depends on db already
      - DB_PORT=3306
      - PORT=3000
    depends_on:
      - db
    ports:
      - "3005:3000"
    container_name: meeting
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh db:3306 -t 20
        npm start
