export const IndexNames = {
  PRODUCT_AND_USER_IN_AUCTION_UNIQUE_INDEX:
    'PRODUCT_AND_USER_IN_AUCTION_UNIQUE_INDEX',
  REASON_AND_USER_IN_POINT_BOOK_INDEX: 'REASON_AND_USER_IN_POINT_BOOK_INDEX',
  UNIQ_TOKEN_IN_POINT_BOOK_UNIQUE_INDEX:
    'UNIQ_TOKEN_IN_POINT_BOOK_UNIQUE_INDEX',
  POINT_DAILY_BOOK_UNIQUE_INDEX: 'POINT_DAILY_BOOK_UNIQUE_INDEX',
}
